### ISSUE TITLE
Bash files for training BiDAF and other models (except Bi-LSTM maxout) 

### ISSUE THREAD

**Issue by vikas95** [allenai/ARC-Solvers#17]
Hi,

Thanks for providing these models, these are very useful resources. 

Do we have bash files (similar to Bi-LSTM maxout model) for training BiDAF model just on ScienceQA datasets ?? I could find instructions for evaluating test data using pre-trained models but couldn't find instructions to train BiDAF or Decomp-att on ScienceQA datasets. 

Other instructions suggested replacing pre-trained BiDAF models with the BiDAF model provided in this repo. 
Do we have to externally train the BiDAF model (i.e. following the original paper) and then replace the trained model in "ARC-V1-models/" directory??

**Comment by tusharkhot** [comment]
Unfortunately Bidaf (designed for RC) and DecompAtt (designed for entailment) can not be directly trained on our multiple-choice questions. And so we had to train them on external science-related datasets. Specifically Bidaf model was trained on science questions by Daniel+Oyvind (described in the SemanticILP paper) and DecompAtt was trained on the SciTail dataset (described in SciTail paper).  I was hoping that by releasing these models, others won’t have to spend time training them on these datasets.

I can release these datasets+steps but it would help me to know what you are trying to do. Do you wish to train a new reading comprehension or entailment model on these datasets ? Or do you have a new dataset that you want to train them on ?

**Comment by vikas95** [comment]
Hi Tushar,

Thanks for the detailed response. We are trying to rerun these models on our enhanced quality of justifications (or passages) for each candidate answer. 

A detailed step by step instructions for training these models would be very helpful. We can convert the questions and our reranked knowledge passages in the required format by looking at your shared datasets (or any examples). 

Quick question on input format - Are the required input formats same as the format of json files generated after running evaluate_bidaf.sh or evaluate_solver.sh ??

Thanks again for all the help and resources.

**Comment by tusharkhot** [comment]
Hi Vikas, 
The instructions for training the entailment model are in the [SciTail repo](https://github.com/allenai/scitail/).
 
Could you create dataset in the SNLI format and train the DecompAtt model as per https://github.com/allenai/scitail#train-the-scitail-models. It relies on the same AllenNLP dependency as this repo, so you should be able to use the same python environment. For the file format: you need to create a dataset in the SNLI format (jsonl with "sentence1", "sentence2" and "gold_label" keys). Once you have trained the model, you can just point the evaluation script to your model directory. Let me know if you have any issues.

I didn't train the BiDAF models so I don't have specific instructions for them. AFAIK,  @OyvindTafjord needed to make some non-trivial changes to AllenNLP to automatically expand the vocabulary when fine-tuning the BiDAF model to the science questions.
